// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using postMortem.Data;

#nullable disable

namespace postMortem.Data.Migrations
{
    [DbContext(typeof(postMortemContext))]
    [Migration("20230921024212_InitialCommentChangeGodHelpUsAll")]
    partial class InitialCommentChangeGodHelpUsAll
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("postMortem.Data.Model.Award", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FromID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ToID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FromID");

                    b.HasIndex("ToID");

                    b.ToTable("Awards");
                });

            modelBuilder.Entity("postMortem.Data.Model.BannedUser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BanReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UntilDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("BannedUsers");
                });

            modelBuilder.Entity("postMortem.Data.Model.Report", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("EntityID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("EntityID");

                    b.HasIndex("UserID");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("postMortem.Data.Model.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("postMortem.Data.Model.Vote", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EntityID")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID1")
                        .HasColumnType("int");

                    b.Property<int>("VoteType")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("EntityID");

                    b.HasIndex("UserID1");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("postMortem.Data.Model.VoteableEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("VoteableEntity");

                    b.HasDiscriminator<string>("Discriminator").HasValue("VoteableEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("postMortem.Data.Model.Comment", b =>
                {
                    b.HasBaseType("postMortem.Data.Model.VoteableEntity");

                    b.Property<int?>("EntityID")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasIndex("EntityID");

                    b.HasIndex("UserID");

                    b.ToTable("VoteableEntity", t =>
                        {
                            t.Property("Message")
                                .HasColumnName("Comment_Message");
                        });

                    b.HasDiscriminator().HasValue("Comment");
                });

            modelBuilder.Entity("postMortem.Data.Model.Post", b =>
                {
                    b.HasBaseType("postMortem.Data.Model.VoteableEntity");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PosterID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("PosterID");

                    b.HasDiscriminator().HasValue("Post");
                });

            modelBuilder.Entity("postMortem.Data.Model.Award", b =>
                {
                    b.HasOne("postMortem.Data.Model.User", "From")
                        .WithMany()
                        .HasForeignKey("FromID");

                    b.HasOne("postMortem.Data.Model.VoteableEntity", "To")
                        .WithMany("AwardsGiven")
                        .HasForeignKey("ToID");

                    b.Navigation("From");

                    b.Navigation("To");
                });

            modelBuilder.Entity("postMortem.Data.Model.BannedUser", b =>
                {
                    b.HasOne("postMortem.Data.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("postMortem.Data.Model.Report", b =>
                {
                    b.HasOne("postMortem.Data.Model.VoteableEntity", "Entity")
                        .WithMany("Reports")
                        .HasForeignKey("EntityID");

                    b.HasOne("postMortem.Data.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("Entity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("postMortem.Data.Model.Vote", b =>
                {
                    b.HasOne("postMortem.Data.Model.VoteableEntity", "Entity")
                        .WithMany("VotesGiven")
                        .HasForeignKey("EntityID");

                    b.HasOne("postMortem.Data.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("postMortem.Data.Model.Comment", b =>
                {
                    b.HasOne("postMortem.Data.Model.VoteableEntity", "Entity")
                        .WithMany("Comments")
                        .HasForeignKey("EntityID");

                    b.HasOne("postMortem.Data.Model.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserID");

                    b.Navigation("Entity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("postMortem.Data.Model.Post", b =>
                {
                    b.HasOne("postMortem.Data.Model.User", "Poster")
                        .WithMany("Posts")
                        .HasForeignKey("PosterID");

                    b.Navigation("Poster");
                });

            modelBuilder.Entity("postMortem.Data.Model.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("postMortem.Data.Model.VoteableEntity", b =>
                {
                    b.Navigation("AwardsGiven");

                    b.Navigation("Comments");

                    b.Navigation("Reports");

                    b.Navigation("VotesGiven");
                });
#pragma warning restore 612, 618
        }
    }
}
